// <copyright file="ApplicationCycle.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>
// Created By:      Itumeleng Oliphant - (on DESKTOP-72504AI)
// Created Date:    12/02/2026 22:19 PM
// Purpose:         Defines the ApplicationCycle class

#region Usings
using ForekOnline.Domain.Shared;
using System.ComponentModel.DataAnnotations.Schema;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents an application cycle, including its period, academic year, and relevant metadata for managing
    /// application windows.
    /// </summary>
    /// <remarks>An application cycle defines the timeframe and context for processing applications, such as
    /// admissions or registrations, within a specific academic year and period. Only one cycle should typically be
    /// active per academic year or period to ensure proper application management. This class includes properties for
    /// tracking status, turnaround times, and audit information, and is intended for use in systems that require
    /// detailed lifecycle management of application windows.</remarks>
    [Table("ApplicationCycle", Schema = "FO")]
    [SkipAuditInterceptor]
    public class ApplicationCycle 
    {
        /// <summary>
        /// Gets or sets the descriptive text associated with the object.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the academic year associated with the entity.
        /// </summary>
        public int AcademicYear { get; set; }

        /// <summary>
        /// Gets or sets the scheduled opening time for the entity.
        /// </summary>
        public DateTime OpensAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the event or period closes.
        /// </summary>
        public DateTime Closes { get; set; }

        /// <summary>
        /// Indicates whether this cycle is currently active. Only one cycle per academic year (or per period if required)
        /// should be active.
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Represents the application period (e.g., Intake, Semester, Trimester). Stored as a string for flexibility.
        /// </summary>
        public string? ApplicationPeriod { get; set; }

        /// <summary>
        /// Turnaround time (TAT) in days for processing applications in this cycle.
        /// </summary>
        public int TurnaroundDays { get; set; }

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the name associated with the object.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}
