// <copyright file="ReportSubReport.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>

#region Usings
using ForekOnline.Domain.Shared;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents an optional sub-report attachment associated with a main report.
    /// </summary>
    [SkipAuditInterceptor]
    public class ReportSubReport
    {
        [Required]
        public Guid ReportId { get; set; }

        /// <summary>
        /// User-defined display name for the file.
        /// </summary>
        [Required]
        [MaxLength(255)]
        public string FileName { get; set; } = string.Empty;

        /// <summary>
        /// Optional short description to help users identify the file.
        /// </summary>
        [MaxLength(250)]
        public string? Description { get; set; }

        /// <summary>
        /// Storage file id (same concept as Report.ReportURL).
        /// </summary>
        [Required]
        public string FileId { get; set; } = string.Empty;

        public DateTime? LastDownloaded { get; set; }

        public int DownloadCount { get; set; } = 0;

        [NotMapped]
        public IFormFile? DocumentFile { get; set; }

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the name associated with the object.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the sub-report.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}