// <copyright file="ResourceCategory.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>

#region Usings
using ForekOnline.Domain.Shared;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents a category of resources.
    /// </summary>
    [SkipAuditInterceptor]
    public class ResourceCategory /*: EntityBase<Guid>*/
    {
        /// <summary>
        /// Gets or sets the collection of resources associated with this category.
        /// </summary>
        public ICollection<Resource> Resources { get; set; } = new List<Resource>();

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the name associated with the object.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        //public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}