// <copyright file="VenueReservationAudit.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>
// Created By:      Itumeleng Oliphant
// Created Date:    15/03/2026
// Purpose:         Audit trail for venue reservation actions

#region Usings
using ForekOnline.Domain.Shared;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static ForekOnline.Domain.Enums.EnumRegistry;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents an audit log entry for a venue reservation action.
    /// </summary>
    [SkipAuditInterceptor]
    public class VenueReservationAudit 
    {
        /// <summary>
        /// Gets or sets the unique identifier for the reservation.
        /// </summary>
        [Required]
        public Guid ReservationId { get; set; }

        /// <summary>
        /// Gets or sets the venue reservation associated with this entity.
        /// </summary>
        [ForeignKey(nameof(ReservationId))]
        public VenueReservation Reservation { get; set; } = null!;

        /// <summary>
        /// Gets or sets the action to perform on the reservation.
        /// </summary>
        /// <remarks>The value must be a valid member of the <see cref="eReservationAction"/> enumeration.
        /// This property is required and determines the operation that will be applied to the reservation, such as
        /// creating, updating, or canceling.</remarks>
        [Required]
        public eReservationAction Action { get; set; }

        /// <summary>
        /// Gets or sets additional notes or comments related to the entity.
        /// </summary>
        [StringLength(500)]
        public string? Remarks { get; set; }

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the venue name.
        /// </summary>
        [Required]
        [StringLength(150)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}