// <copyright file="Venue.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>
// Created By:      Itumeleng Oliphant
// Created Date:    15/03/2026
// Purpose:         Defines the Venue entity for venue master data management (FR-01)

#region Usings
using ForekOnline.Domain.Shared;
using System.ComponentModel.DataAnnotations;
using static ForekOnline.Domain.Enums.EnumRegistry;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents a physical venue available for assessment bookings.
    /// </summary>
    [SkipAuditInterceptor]
    public class Venue
    {
        /// <summary>
        /// Gets or sets the campus where the venue is located.
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Campus { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the departments associated with this venue (pipe-delimited for multi-select).
        /// </summary>
        public eDepartment Departments { get; set; } 

        /// <summary>
        /// Gets or sets the maximum seating capacity.
        /// </summary>
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Capacity must be greater than 0.")]
        public int MaxCapacity { get; set; }

        /// <summary>
        /// Gets or sets the venue type.
        /// </summary>
        [Required]
        public eVenueType VenueType { get; set; }

        /// <summary>
        /// Gets or sets the equipment checklist (pipe-delimited).
        /// </summary>
        [StringLength(1000)]
        public string? EquipmentChecklist { get; set; }

        /// <summary>
        /// Gets or sets the default booking rules description.
        /// </summary>
        [StringLength(500)]
        public string? DefaultBookingRules { get; set; }

        /// <summary>
        /// Gets or sets the photo URL or file ID.
        /// </summary>
        [StringLength(500)]
        public string? PhotoUrl { get; set; }

        /// <summary>
        /// Gets or sets the floor plan URL or file ID.
        /// </summary>
        [StringLength(500)]
        public string? FloorPlanUrl { get; set; }

        /// <summary>
        /// Gets or sets the venue status.
        /// </summary>
        [Required]
        public eVenueStatus Status { get; set; } = eVenueStatus.Active;

        /// <summary>
        /// Navigation property – reservations made for this venue.
        /// </summary>
        public ICollection<VenueReservation> Reservations { get; set; } = new List<VenueReservation>();

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the venue name.
        /// </summary>
        [Required]
        [StringLength(150)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}