// <copyright file="VenueAssessmentBooking.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>
// Created By:      Itumeleng Oliphant
// Created Date:    15/03/2026
// Purpose:         Links an approved reservation to a sent assessment (FR-04)

#region Usings
using ForekOnline.Domain.Shared;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static ForekOnline.Domain.Enums.EnumRegistry;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents a confirmed assessment booking on an HOD-approved venue reservation.
    /// Once created, the venue slot becomes permanently booked.
    /// </summary>
    [SkipAuditInterceptor]
    public class VenueAssessmentBooking 
    {
        /// <summary>
        /// Gets or sets the approved reservation this booking is linked to.
        /// </summary>
        [Required]
        public Guid ReservationId { get; set; }

        /// <summary>
        /// Gets or sets the venue reservation associated with this entity.
        /// </summary>
        [ForeignKey(nameof(ReservationId))]
        public VenueReservation Reservation { get; set; } = null!;

        /// <summary>
        /// Gets or sets the course ID for the assessment.
        /// </summary>
        [Required]
        public Guid CourseId { get; set; }

        /// <summary>
        /// Gets or sets the module ID for the assessment.
        /// </summary>
        [Required]
        public Guid ModuleId { get; set; }

        /// <summary>
        /// Gets or sets the assessment name / title.
        /// </summary>
        [Required]
        [StringLength(200)]
        public string AssessmentName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the assessment type description.
        /// </summary>
        public eAssessmentType? AssessmentType { get; set; }

        /// <summary>
        /// Gets or sets the instructions for students.
        /// </summary>
        [StringLength(2000)]
        public string? Instructions { get; set; }

        /// <summary>
        /// Gets or sets the assessment duration in minutes.
        /// </summary>
        public int? DurationMinutes { get; set; }

        /// <summary>
        /// Gets or sets the student ID/Passport numbers (pipe-delimited) enrolled for this booking.
        /// </summary>
        [Required]
        public string StudentList { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether student emails have been sent.
        /// </summary>
        public bool EmailsSent { get; set; }

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the venue name.
        /// </summary>
        [Required]
        [StringLength(150)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}