// <copyright file="VenueReservation.cs" company="Forek ICT Services">
//     Copyright © Forek ICT Services.
// </copyright>
// Created By:      Itumeleng Oliphant
// Created Date:    15/03/2026
// Purpose:         Defines the VenueReservation entity for Stage 1 reservation workflow (FR-02, FR-03)

#region Usings
using ForekOnline.Domain.Shared;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static ForekOnline.Domain.Enums.EnumRegistry;
#endregion

namespace ForekOnline.Domain.Entities
{
    /// <summary>
    /// Represents a venue reservation (Stage 1 – soft hold pending HOD approval).
    /// </summary>
    public class VenueReservation 
    {
        /// <summary>
        /// Gets or sets the venue foreign key.
        /// </summary>
        [Required]
        public Guid VenueId { get; set; }

        /// <summary>
        /// Navigation property to the venue.
        /// </summary>
        [ForeignKey(nameof(VenueId))]
        public Venue Venue { get; set; } = null!;

        /// <summary>
        /// Gets or sets the ID of the facilitator who created the reservation.
        /// </summary>
        [Required]
        public Guid FacilitatorId { get; set; }

        /// <summary>
        /// Gets or sets the facilitator display name.
        /// </summary>
        [Required]
        [StringLength(120)]
        public string FacilitatorName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the campus for this reservation.
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Campus { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the expected number of students.
        /// </summary>
        [Required]
        [Range(1, int.MaxValue)]
        public int ExpectedStudents { get; set; }

        /// <summary>
        /// Gets or sets the reserved date.
        /// </summary>
        [Required]
        public DateTime ReservedDate { get; set; }

        /// <summary>
        /// Gets or sets the start time (UTC).
        /// </summary>
        [Required]
        public DateTime StartTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the end time (UTC).
        /// </summary>
        [Required]
        public DateTime EndTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets the current reservation status.
        /// </summary>
        [Required]
        public eReservationStatus Status { get; set; } = eReservationStatus.PendingHodApproval;

        /// <summary>
        /// Gets or sets the HOD rejection reason (mandatory on reject).
        /// </summary>
        [StringLength(500)]
        public string? RejectionReason { get; set; }

        /// <summary>
        /// Gets or sets the ID of the HOD who actioned the reservation.
        /// </summary>
        public Guid? ActionedByHodId { get; set; }

        /// <summary>
        /// Gets or sets the name of the HOD who actioned the reservation.
        /// </summary>
        [StringLength(120)]
        public string? ActionedByHodName { get; set; }

        /// <summary>
        /// Gets or sets when the HOD actioned this reservation (UTC).
        /// </summary>
        public DateTime? ActionedOnUtc { get; set; }

        /// <summary>
        /// Gets or sets the 72-hour auto-expiry deadline (UTC).
        /// </summary>
        [Required]
        public DateTime ExpiresOnUtc { get; set; }

        /// <summary>
        /// Navigation – audit log entries.
        /// </summary>
        public ICollection<VenueReservationAudit> AuditLog { get; set; } = new List<VenueReservationAudit>();

        #region IEntity

        /// <summary>
        /// Gets or sets the unique code that identifies the entity.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Gets or sets the venue name.
        /// </summary>
        [Required]
        [StringLength(150)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the database row version used for concurrency control.
        /// </summary>
        /// <remarks>The row version is typically a timestamp or binary value generated by the database to
        /// detect changes to a record. Use this property when implementing optimistic concurrency to ensure updates are
        /// not overwritten by other operations.</remarks>
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was created.
        /// </summary>
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was last modified.
        /// </summary>
        public DateTimeOffset DateModified { get; set; }

        /// <summary>
        /// Gets or sets the username of the user who created the entity.
        /// </summary>
        public string? UserCreated { get; set; }

        /// <summary>
        /// Gets or sets the name of the user who last modified the entity.
        /// </summary>
        public string? UserModified { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been marked as deleted.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the entity was deleted.
        /// </summary>
        public DateTimeOffset? DateDeleted { get; set; }
        #endregion
    }
}